name: Publish new package

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*d'

jobs:
  build_manylinux:
    name: Build for manylinux
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2010_x86_64

    steps:        
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        git clone https://github.com/eigenteam/eigen-git-mirror
        cd eigen-git-mirror
        git checkout tags/3.3.7
        cd ..
        mkdir include
        mv eigen-git-mirror/Eigen/ include/
        rm -rf eigen-git-mirror/
    - name: Deploy
      continue-on-error: True
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        /opt/python/cp35-cp35m/bin/python -m pip install twine wheel numpy
        /opt/python/cp35-cp35m/bin/python setup.py sdist
        /opt/python/cp35-cp35m/bin/python -m twine upload dist/*.tar.gz
        for cp in cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38
        do
          /opt/python/${cp}/bin/python -m pip install twine wheel numpy
          /opt/python/${cp}/bin/python setup.py build bdist_wheel
          auditwheel repair dist/*-${cp}-linux_x86_64.whl
        done
        /opt/python/cp38-cp38/bin/python -m twine upload wheelhouse/*.whl

  build_macos:
    name: Build for macOS
    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        wget https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz
        tar -zxvf 3.3.7.tar.gz
        mv eigen-git-mirror-3.3.7 include
    - name: Deploy
      continue-on-error: True
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        export AUDITWHEEL_PLAT=many
        python -m pip install twine wheel numpy
        python setup.py bdist_wheel
        twine upload dist/*

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        Invoke-WebRequest -OutFile 3.3.7.tar.gz https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz
        tar -zxvf 3.3.7.tar.gz
        mv eigen-git-mirror-3.3.7 include
    - name: Deploy
      continue-on-error: True
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install twine wheel numpy
        python setup.py bdist_wheel
        twine upload dist/*
