name: Pull Request Test

on: 
  pull_request:
    branches: 
      - main

jobs:
  build_manylinux:
    name: Build for manylinux
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2010_x86_64
    strategy:
      max-parallel: 4
      matrix:
        cp: [cp35-cp35m, cp36-cp36m, cp37-cp37m, cp38-cp38]

    steps:        
    - uses: actions/checkout@v1
    - name: Print Info
      run: |
        cat /proc/cpuinfo
    - name: Install dependencies
      run: |
        git clone https://github.com/eigenteam/eigen-git-mirror
        cd eigen-git-mirror
        git checkout tags/3.3.7
        cd ..
        mv eigen-git-mirror include
    - name: Build
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install numpy
        /opt/python/${{ matrix.cp }}/bin/python setup.py build install
    - name: Test
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install pytest
        /opt/python/${{ matrix.cp }}/bin/python -m pytest --verbose -s test/unit_test.py

  build_macos:
    name: Build for macOS
    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        wget https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz
        tar -zxvf 3.3.7.tar.gz
        mv eigen-git-mirror-3.3.7 include
    - name: Build
      run: |
        python -m pip install numpy
        python setup.py build install
    - name: Test
      run: |
        python -m pip install pytest
        python -m pytest --verbose -s test/unit_test.py

  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt
        Invoke-WebRequest -OutFile 3.3.7.tar.gz https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz
        tar -zxvf 3.3.7.tar.gz
        mv eigen-git-mirror-3.3.7 include
    - name: Build
      run: |
        python -m pip install numpy
        python setup.py build install
    - name: Test
      run: |
        python -m pip install pytest
        python -m pytest --verbose -s test/unit_test.py
